In [ ]:
#module 1
#numpy exercise
import numpy as np
x = np.random.randint(10,30,6)
print(x)

[22 23 15 20 24 19]


In [ ]:
import numpy as np
x = np.random.randint((10,5))
print(x)
new=x[:5]
print(new)

[5 0]
[5 0]


In [ ]:
import numpy as np
x=np.random.random((5,5))
print(x)
max,max=x.max(),x.min()
print(max,min)

[[0.95172443 0.63637666 0.74425597 0.7234495  0.07552529]
 [0.97186503 0.20312665 0.25953769 0.92703151 0.65690777]
 [0.25041916 0.5116859  0.98228641 0.62844417 0.68028571]
 [0.02079557 0.16163704 0.26802245 0.57594927 0.25099012]
 [0.44062845 0.45263583 0.92024104 0.9270603  0.4134478 ]]
0.020795567365681555 <built-in function min>


In [ ]:
import numpy as np
x=np.arange(1,11)
print(x)
np.random.shuffle(x)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]
[ 5  8  2  6  1  4 10  7  9  3]


In [ ]:
import numpy as np
x = np.random.randint(0,10,40)
print("The original array:",x)
print("The most freq value is ",np.bincount(x).argmax())
print("The least freq value is",np.bincount(x).argmin())

The original array: [8 7 5 0 4 6 2 3 2 1 2 3 5 5 1 0 1 5 7 6 6 7 8 8 1 2 9 0 3 3 3 6 9 5 8 1 1
 6 2 8]
The most freq value is  1
The least freq value is 4


In [ ]:
#broadcasting
import numpy as np
a = np.array([1,3,0],float)
print(a>2)

[False  True False]


In [ ]:
import numpy as np
a = np.array([2,3,4])
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
#2d array
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:

arr=np.array((3,3),int)
print(arr)

[3 3]


In [ ]:
arr=np.ones((3,3)),int
print(arr)

(array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]]), <class 'int'>)


In [ ]:
import numpy as np
arr=np.arange(10,30,5) #Changed 'arrange' to 'arange'
arr=np.arange(0,2,0.3) #Changed 'arrange' to 'arange'
print(arr)

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [ ]:
import numpy as np
arr=np.linspace(0,2,9)
print(arr)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [ ]:
import numpy as np
arr=np.identity(3,int)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
import numpy as np
A=np.array([1,4,5],int)
for x in A:
    print(x,end=",")

1,4,5,

In [ ]:
A=np.array([[1,2],[3,4],[5,6]])
for x in A:
    print(x,end=",")

[1 2],[3 4],[5 6],

In [ ]:
for(x,y) in A:
  print(x*y,end=",")

2,12,30,

In [ ]:
a=np.array([10,20,30,40])
b=np.arange(4)
c=a-b
print(c)
print(b**2)

[10 19 28 37]
[0 1 4 9]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a*b)

[[ 5 12]
 [21 32]]


In [ ]:
import numpy as np
n = input("Enter the number of characters: ")
l=[]
for i in range(n):
    c=input("Enter the character: ")
    l.append(c)
n=np.array(l)
print(type(n))
vowels=['a','e','i','o','u','A','E','I','O','U']
cv=0
cu=0
cl=0
for c in n:
    if c in vowels:
        cv=cv+1
    if c.islower():
        cl=cl+1
    if c.isupper():
        cu=cu+1

print("The number of vowels are",cv)
print("The number of lowercase characters are",cl)
print("The number of uppercase characters are",cu)

Invalid input. Please enter a number.
Invalid input. Please enter a number.
Enter the number of characters: a
Invalid input. Please enter a number.


KeyboardInterrupt: Interrupted by user

In [33]:
import numpy as np
n=int(input("Enter the number of elements: "))
l=[]
l_out=[] # initialize l_out here
for i in range(n):
    c=input("Enter the character: ")
    l.append(c)
n=np.array(l) # reduce indent
print(type(n))
cv=0
cu=0
cl=0
for c in n:
  if c.islower():
    l_out.append(c.upper())
  if c.isupper():
    l_out.append(c.lower())
print(l_out)

Enter the number of elements: 1
Enter the character: A
<class 'numpy.ndarray'>
['a']


In [35]:
import numpy as np
a = eval(input("Enter the element of matrix A as a list of list"))
b = eval(input("Enter the element of matrix B as a list of list"))
a1 = np.array(a)
b1= np.array(b)
print("The sum of the matrics a and b",c)

KeyboardInterrupt: Interrupted by user

In [36]:
l=[]
r=int(input("Enter the number of rows: "))
c=int(input("Enter the number of columns: "))
if r==c:
  print("Enter A matrix")
  for i in range(0,r):
    li=[]
    for j in range(0,c):
      x=int(input("Enter A[{0}][{1}]".format(i,j)))
      li.append(x)
    l.append(li)
  a=np.array(l)
  print(a)

Enter the number of rows: 1
Enter the number of columns: 1
Enter A matrix
Enter A[0][0]45
[[45]]


In [37]:
d1=d2=x=0
y=c-1
for i in range(0,r):
  for j in range(0,c):
    if i==j:
      d1=d1+a[i][j]
    if x==y:
      d2=d2+a[x][y]
      x=x-1
      y=y-1
  print("Sum of diagonal1=",d1)
  print("Sum of daiagonal2",d2)
else:
  print("Not a square Matrix")

Sum of diagonal1= 45
Sum of daiagonal2 45
Not a square Matrix


In [38]:
a=np.array([1,2])
b=np.array([3,4])
c=np.array([5,6])
print(np.concatenate((a,b,c)))
#

[1 2 3 4 5 6]


In [39]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
np.concatenate((a,b),axis=0)
np.concatenate((a,b),axis=1)


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [40]:
A=np.array([2,1,9])
print(a.argmin())
print(a.argmax())
#

0
3


In [43]:
A=np.array([[3,2],[5,6]]) # enclose the lists [3,2] and [5,6] within another list
print(A.argmin(axis=0))
print(A.argmin(axis=1))
print(A.argmax(axis=0))
print(A.argmax(axis=1))

[0 0]
[1 0]
[1 1]
[0 1]


In [44]:
A=np.array([6,2,5,-1,0])
print(np.sort(A))

[-1  0  2  5  6]


In [45]:
A=np.array([1,1,4,5,5,7])
print(np.unique(A))

[1 4 5 7]


In [49]:
A=np.array([[1,2],[3,4]])
print(A.diagonal())

[1 4]


In [52]:
A=np.arange(10)**3
print(A)


[  0   1   8  27  64 125 216 343 512 729]


In [53]:
A=np.array([[1,2],[3,4]])
print(A.transpose())

[[1 3]
 [2 4]]


In [54]:
x=np.arange(0,10)
print(x)
x=x.reshape(5,2)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [55]:
x=np.array([[0,1,2],[3,4,5,],[6,7,8]])
x.flatten()
x.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
import numpy as np
a=np.array([1,3,0],float)
b=np.array([0,3,2],float)
print(a>b)

[ True False False]


In [57]:
import numpy as np
x = np.random.randint(1,100)
c=np.random.randint(8)
print(x+c)

24


In [58]:
a=np.array([0,1,4,2,5,2,5,6,3,9])
print(a.mean())

3.7


In [60]:
print(a.var())

6.410000000000001


In [61]:
print(a.std())

2.5317977802344327


In [64]:
print(np.median(a))

3.5


In [65]:
print(np.cov(a))

7.122222222222223


In [66]:
a=np.array([[5,9,8],[4,11,6],[7,15,10]])
b=np.array([[0,-1,2],[4,6,10],[3,1,5]])
a-=2
b+=3
b=b.transpose()
x=(np.dot(b,np.linalg.inv(a)))
print(np.rint(x))

[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]


In [67]:
a=np.array([1,4,9],float)
print(np.sqrt(a))

[1. 2. 3.]


In [68]:
a=np.array([1.1,1.5,1.9],float)
print(np.floor(a))

[1. 1. 1.]


In [70]:
print(np.ceil(a))

[2. 2. 2.]


In [71]:
print(np.rint(a))

[1. 2. 2.]


In [72]:
print(np.pi)

3.141592653589793


In [73]:
print(np.e)

2.718281828459045


In [74]:
a=np.array([1,2,3],float)
print(np.sqrt(a))

[1.         1.41421356 1.73205081]


In [75]:
a=np.array([[4,20,0],[9,3,7],[1,2,1]])
print(np.linalg.det(a))

-83.99999999999999


In [76]:
vals,vecs=np.linalg.eig(a)
print(vals)
print(vecs)
#

[ 17.64697688 -10.11745319   0.47047632]
[[-0.82039505 -0.81659788 -0.62940553]
 [-0.55979561  0.57641412  0.11107509]
 [-0.11653685 -0.03024347  0.76909753]]


In [77]:
b=np.linalg.inv(a)
print(b)

[[ 0.13095238  0.23809524 -1.66666667]
 [ 0.02380952 -0.04761905  0.33333333]
 [-0.17857143 -0.14285714  2.        ]]


In [80]:
a=np.array([0,1,2,3,4,5])
index=np.array([0,2,4])
new_val=np.array([100,200,300])
a.put(index,new_val)
print(a)

[100   1 200   3 300   5]


In [82]:
b=np.array([100,200,300,400,500])
b.put(index,5)
print(b)

[  5 200   5 400   5]


In [83]:
a=np.array([2,4,6,8])
index1=[0,0,1,1,1]
print(a.take(index1))

[2 2 4 4 4]


In [84]:
arr=np.array([[2,4,6,8],[1,3,5,7]])
index1=np.array([0,1,0,1])
index2=np.array([0,1,2,3])
print(arr.take(index1,axis=0))
print(arr.take(index2,axis=1))

[[2 4 6 8]
 [1 3 5 7]
 [2 4 6 8]
 [1 3 5 7]]
[[2 4 6 8]
 [1 3 5 7]]


In [85]:
a=np.array([2,4,6,8])
index=np.array([0,0,1,1,1])
t=a[index]
print(t)

[2 2 4 4 4]


In [86]:
a=np.array([[6,4],[5,9]])
sel = (a>=6)
print(a[sel])

[6 9]


In [87]:
a=np.array([9,5,6,2,9,3,1])
b=np.logical_and(a>3,a<9)
print(b)

[False  True  True False False False False]


In [88]:
x=np.logical_or(a>3,a<9)
print(x)

[ True  True  True  True  True  True  True]


In [89]:
x=np.logical_not(a>3,a<9)
print(x)

[False False False  True False  True  True]


In [90]:
import numpy as np
a=np.array([0,2,5,3,0,9,-1,0,8])
b=np.array([3,0,2,5,4,0])
print(a.nonzero())
print(b.nonzero())

(array([1, 2, 3, 5, 6, 8]),)
(array([0, 2, 3, 4]),)


In [91]:
import numpy as np
a = np.array([1,3,0],float)
b = np.array([0,3,2],float)
print(a>b)

[ True False False]


In [93]:
c=np.array([True,False,True,False])
any(c)

True

In [94]:
all(c)

False